# Generated by Django 3.2 on 2022-10-18 21:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_profile_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('region1', models.TextField(blank=True, null=True)),
                ('region2', models.TextField(blank=True, null=True)),
                ('region3', models.TextField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('benefit', models.TextField(blank=True, null=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='like_location', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
            ],
            options={
                'db_table': 'locations_location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, upload_to='reviews/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='게시자')),
                ('likes', models.ManyToManyField(blank=True, related_name='like_review', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='locations.location', verbose_name='업소')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.profile', verbose_name='프로필')),
            ],
            options={
                'db_table': 'locations_review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocationUserStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='locations.location', verbose_name='업소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_location', to=settings.AUTH_USER_MODEL, verbose_name='평가자')),
            ],
            options={
                'db_table': 'locations_user_star',
                'managed': True,
            },
        ),
    ]
