# Generated by Django 3.2 on 2022-10-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('benefit', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crawled_data',
                'managed': False,
            },
        ),
    ]
