# Generated by Django 3.2 on 2022-10-10 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_profile_nickname'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, upload_to='review/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='locations.location', verbose_name='업소')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='게시자')),
                ('likes', models.ManyToManyField(blank=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.profile', verbose_name='프로필')),
            ],
            options={
                'db_table': 'locations_review',
                'managed': True,
            },
        ),
    ]
