# Generated by Django 3.2 on 2022-10-23 12:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mou',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('benefit', models.TextField(blank=True, null=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='like_Mou', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
            ],
            options={
                'db_table': 'MOU_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MouUserStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='locations.mou', verbose_name='업소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_Mou', to=settings.AUTH_USER_MODEL, verbose_name='평가자')),
            ],
            options={
                'db_table': 'Mou_user_star',
                'managed': True,
            },
        ),
    ]
