# Generated by Django 3.2 on 2022-10-23 23:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_profile_nickname'),
        ('locations', '0002_mou_mouuserstar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='LocationReview',
        ),
    ]
