# Generated by Django 3.2 on 2022-10-24 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_profile_nickname'),
        ('locations', '0003_rename_review_locationreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_review', to=settings.AUTH_USER_MODEL, verbose_name='게시자'),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='image',
            field=models.ImageField(blank=True, upload_to='location_reviews/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_location_review', to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_review', to='locations.location', verbose_name='업소'),
        ),
        migrations.AlterField(
            model_name='locationreview',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_review', to='accounts.profile', verbose_name='프로필'),
        ),
        migrations.CreateModel(
            name='MouReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, upload_to='mou_reviews/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='게시자')),
                ('likes', models.ManyToManyField(blank=True, related_name='like_mou_review', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
                ('mou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='locations.mou', verbose_name='업소')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.profile', verbose_name='프로필')),
            ],
            options={
                'db_table': 'Mou_review',
                'managed': True,
            },
        ),
    ]
