# Generated by Django 3.2 on 2022-10-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20221024_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('pstnexpln', models.TextField(blank=True, null=True)),
                ('wkday_strtm', models.TextField(blank=True, null=True)),
                ('wkday_endtm', models.TextField(blank=True, null=True)),
                ('wkend_strtm', models.TextField(blank=True, null=True)),
                ('wkend_endtm', models.TextField(blank=True, null=True)),
                ('etc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TMO_data',
                'managed': True,
            },
        ),
    ]
