# Generated by Django 4.1.1 on 2022-09-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/default.png", upload_to="profile/"
            ),
        ),
    ]
