# Generated by Django 4.1.1 on 2022-09-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/default/default.png", upload_to="profile/"
            ),
        ),
    ]
