# Generated by Django 3.2 on 2022-10-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_rename_image_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nickname', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(default='profile/default/default.png', upload_to='profile/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
