# Generated by Django 4.1.1 on 2022-09-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="post/", verbose_name="이미지"),
        ),
    ]
