# Generated by Django 2.2.4 on 2022-09-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220912_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default/default_post_img.png', upload_to='posts/img'),
        ),
    ]
